/**
 * Mintmark — Supabase Database Types
 *
 * Matches the schema in supabase/schema.sql exactly.
 * Format mirrors Supabase CLI `supabase gen types typescript` output so
 * the generated client types (`createClient<Database>`) work correctly.
 *
 * Usage:
 *   import { createClient } from '@supabase/supabase-js'
 *   import type { Database } from '@/types/database'
 *   const supabase = createClient<Database>(url, key)
 *
 *   // Fully typed row access:
 *   const { data } = await supabase.from('waitlist').select('*')
 *   //    ^ data is WaitlistRow[] | null
 *
 * Helper aliases at the bottom of this file:
 *   Tables<'waitlist'>         → Row type
 *   TablesInsert<'waitlist'>   → Insert type
 *   TablesUpdate<'waitlist'>   → Update type
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // -----------------------------------------------------------------------
      // users
      // -----------------------------------------------------------------------
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          avatar: string | null
          /** bcrypt hash; set by accept_invite_account RPC only */
          password_hash: string
          /** 'user' | 'admin' — default 'user' */
          role: UserRole
          created_at: string
        }
        Insert: {
          /** Defaults to gen_random_uuid() */
          id?: string
          email: string
          name?: string | null
          avatar?: string | null
          password_hash: string
          role?: UserRole
          /** Defaults to now() */
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          avatar?: string | null
          password_hash?: string
          role?: UserRole
          created_at?: string
        }
        Relationships: []
      }

      // -----------------------------------------------------------------------
      // waitlist
      // -----------------------------------------------------------------------
      waitlist: {
        Row: {
          id: string
          email: string
          name: string | null
          reason: string | null
          /** Auto-generated 8-char uppercase alphanumeric code */
          referral_code: string
          /** referral_code of whoever referred this person */
          referred_by: string | null
          /** Denormalized position; effective position via get_waitlist_position() */
          position: number | null
          /** 'waiting' | 'invited' | 'joined' */
          status: WaitlistStatus
          email_verified: boolean
          verification_token: string | null
          created_at: string
        }
        Insert: {
          id?: string
          email: string
          name?: string | null
          reason?: string | null
          /** Leave blank — auto-generated by trigger */
          referral_code?: string
          referred_by?: string | null
          position?: number | null
          status?: WaitlistStatus
          email_verified?: boolean
          verification_token?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          reason?: string | null
          referral_code?: string
          referred_by?: string | null
          position?: number | null
          status?: WaitlistStatus
          email_verified?: boolean
          verification_token?: string | null
          created_at?: string
        }
        Relationships: []
      }

      // -----------------------------------------------------------------------
      // invite_tokens
      // -----------------------------------------------------------------------
      invite_tokens: {
        Row: {
          id: string
          email: string
          token: string
          expires_at: string
          /** Set when the token is consumed; null = still valid */
          used_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          email: string
          token: string
          expires_at: string
          used_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          token?: string
          expires_at?: string
          used_at?: string | null
          created_at?: string
        }
        Relationships: []
      }

      // -----------------------------------------------------------------------
      // system_config
      // -----------------------------------------------------------------------
      system_config: {
        Row: {
          /** Config key, e.g. "early_access_limit" */
          key: string
          /** Serialised config value (always stored as text) */
          value: string
          updated_at: string
        }
        Insert: {
          key: string
          value: string
          updated_at?: string
        }
        Update: {
          key?: string
          value?: string
          updated_at?: string
        }
        Relationships: []
      }

      // -----------------------------------------------------------------------
      // user_settings
      // -----------------------------------------------------------------------
      user_settings: {
        Row: {
          /** PK and FK → users.id */
          user_id: string
          theme: UserTheme
          timezone: string
          active_platforms: string
          created_at: string
        }
        Insert: {
          user_id: string
          theme?: UserTheme
          timezone?: string
          active_platforms?: string
          created_at?: string
        }
        Update: {
          user_id?: string
          theme?: UserTheme
          timezone?: string
          active_platforms?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_settings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
    }

    Views: {
      [_ in never]: never
    }

    Functions: {
      /**
       * generate_referral_code — trigger function, not called directly.
       * Listed here for completeness.
       */
      generate_referral_code: {
        Args: Record<PropertyKey, never>
        Returns: unknown  // trigger return type
      }

      /**
       * Returns the effective waitlist position for an email address.
       * Accounts for referral bonuses (-5 spots per referral, min 1).
       * Returns null if the email is not on the waitlist.
       *
       * @example
       * const { data } = await supabase
       *   .rpc('get_waitlist_position', { p_email: 'user@example.com' })
       * // data: number | null
       */
      get_waitlist_position: {
        Args: {
          p_email: string
        }
        Returns: number | null
      }

      /**
       * Atomically creates a user account from a valid invite token.
       * Returns { error: string } on failure or { user_id, email, name } on success.
       */
      accept_invite_account: {
        Args: {
          p_token: string
          p_name: string
          p_password_hash: string
          p_timezone?: string
        }
        Returns: Json
      }

      /**
       * Returns paginated waitlist rows with referral counts (no N+1).
       */
      get_admin_waitlist: {
        Args: {
          p_page?: number
          p_limit?: number
          p_status?: string | null
          p_search?: string | null
        }
        Returns: Json
      }
    }

    Enums: {
      [_ in never]: never
    }

    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// =============================================================================
// Enum types (mirrors CHECK constraints in schema.sql)
// =============================================================================

export type WaitlistStatus = "waiting" | "invited" | "joined"

export type UserTheme = "dark" | "light"

export type UserRole = "user" | "admin"

// =============================================================================
// Helper type aliases — mirror the Supabase CLI output pattern
// =============================================================================

type PublicSchema = Database["public"]

/** Row type for a table. Usage: Tables<'waitlist'> */
export type Tables<
  T extends keyof PublicSchema["Tables"],
> = PublicSchema["Tables"][T]["Row"]

/** Insert type for a table. Usage: TablesInsert<'waitlist'> */
export type TablesInsert<
  T extends keyof PublicSchema["Tables"],
> = PublicSchema["Tables"][T]["Insert"]

/** Update type for a table. Usage: TablesUpdate<'waitlist'> */
export type TablesUpdate<
  T extends keyof PublicSchema["Tables"],
> = PublicSchema["Tables"][T]["Update"]

/** Convenience: a row from the waitlist table */
export type WaitlistRow = Tables<"waitlist">

/** Convenience: a row from the users table */
export type UserRow = Tables<"users">

/** Convenience: a row from the invite_tokens table */
export type InviteTokenRow = Tables<"invite_tokens">

/** Convenience: a row from the user_settings table */
export type UserSettingsRow = Tables<"user_settings">

/** Convenience: a row from the system_config table */
export type SystemConfigRow = Tables<"system_config">
